# Generated by Django 3.2 on 2021-05-16 22:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Entity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('validity_flag', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Directory',
            fields=[
                ('entity_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='utils.entity')),
                ('name', models.CharField(max_length=50)),
                ('description', models.CharField(blank=True, default='', max_length=255)),
                ('creation_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('availability_flag', models.BooleanField(default=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('parent_dir', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='utils.directory')),
            ],
            bases=('utils.entity',),
        ),
        migrations.CreateModel(
            name='File',
            fields=[
                ('entity_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='utils.entity')),
                ('name', models.CharField(max_length=50)),
                ('description', models.CharField(blank=True, default='', max_length=255)),
                ('creation_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('availability_flag', models.BooleanField(default=True)),
                ('content', models.FileField(default='', upload_to='users_files/')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('parent_dir', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='utils.directory')),
            ],
            bases=('utils.entity',),
        ),
        migrations.CreateModel(
            name='FileSection',
            fields=[
                ('entity_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='utils.entity')),
                ('name', models.CharField(blank=True, default='', max_length=50)),
                ('description', models.CharField(blank=True, default='', max_length=255)),
                ('creation_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('parent_file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='utils.file')),
                ('parent_section', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='utils.filesection')),
            ],
            bases=('utils.entity',),
        ),
        migrations.CreateModel(
            name='SectionStatus',
            fields=[
                ('entity_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='utils.entity')),
                ('status', models.CharField(max_length=50)),
                ('section', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='utils.filesection')),
            ],
            bases=('utils.entity',),
        ),
        migrations.CreateModel(
            name='SectionData',
            fields=[
                ('entity_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='utils.entity')),
                ('status_data', models.CharField(max_length=255)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('section_status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='utils.sectionstatus')),
            ],
            bases=('utils.entity',),
        ),
        migrations.CreateModel(
            name='SectionCategory',
            fields=[
                ('entity_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='utils.entity')),
                ('category', models.CharField(choices=[('procedure', 'procedure'), ('property', 'property'), ('lemma', 'lemma'), ('assertion', 'assertion'), ('invariant', 'invariant'), ('precondition', 'precondition'), ('postcondition', 'postcondition')], max_length=32)),
                ('section', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='utils.filesection')),
            ],
            bases=('utils.entity',),
        ),
    ]
