# Generated by Django 3.2 on 2021-05-19 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utils', '0006_alter_file_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='content',
            field=models.FileField(default='', upload_to='users_files/'),
        ),
    ]
